on:
    workflow_dispatch:
    push:
      branches:
        - main
        - exploring-workflow

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}  # 'superuser'
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} #'SuperPassword'
  
jobs:
    unit-testing:
      name: Unit Testing
      strategy:
        matrix:
          os: [ubuntu-latest]
          node-v: [20] 
          exclude:
            - node-v: 18
              os: macos-latest
  
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Setup Node Version - ${{ matrix.node-v }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-v }}

        - name : Cache NPM Dependency
          uses : actions/cache@v3
          with: 
            path: node_modules
            key : ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}
  
        - name: Install Dependencies
          run: npm install
  
        - name: Unit Testing
          id : nodejs-testing-step
          run: npm test
  
        - name: Archive Test Result
          if : always()
          uses: actions/upload-artifact@v3
          with:
            name: Mocha Test Result
            path: test-results.xml
    
    code_coverage : 
      name: Code Coverage
      # strategy:
      #   matrix:
      #     os: [ubuntu-latest, macos-latest]
      #     node-v: [18, 19, 20]
      #     exclude:
      #       - node-v: 18
      #         os: macos-latest
  
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Setup Node Version - 18
          uses: actions/setup-node@v4
          with:
            node-version: 18

        - name : Cache NPM Dependency
          uses : actions/cache@v3
          with: 
            path: node_modules
            key : ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}
  
        - name: Install Dependencies
          run: npm install
  
        - name: Check Code Coverage
          continue-on-error: true
          run: npm run coverage
  
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Code coverage reult 
            path: coverage
            retention-days: 5

    docker:
      name: Containerization
      needs: [code_coverage, unit-testing]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
    
        - name: GITHUB Login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io 
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Dockerhub Login
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        - name: Docker build for Testing
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
    
        - name: Docker Image Testing
          run: |
            docker images
            docker run --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI=$MONGO_URI \
                -e MONGO_USERNAME=$MONGO_USERNAME \
                -e MONGO_PASSWORD=$MONGO_PASSWORD \
                ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
    
            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo $IP
    
            echo Testing image URL using wget
            wget -q -O - 127.0.0.1:3000/live | grep live

        - name: Container registry push 
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: |
              ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}