on:
    workflow_dispatch:
    push:
      branches:
        - main
        - exploring-workflow

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}  # 'superuser'
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} #'SuperPassword'
  
jobs:
    unit-testing:
      name: Unit Testing
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
          node-v: [18, 19, 20]
          exclude:
            - node-v: 18
              os: macos-latest
  
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Setup Node Version - ${{ matrix.node-v }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-v }}
  
        - name: Install Dependencies
          run: npm install
  
        - name: Unit Testing
          run: npm test
  
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha Test Result
            path: test-results.xml
  