on:
    workflow_dispatch:
    push:
      branches:
        - main
        - exploring-workflow

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}  # 'superuser'
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} #'SuperPassword'
  
jobs:
    unit-testing:
      name: Unit Testing
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
          node-v: [18, 19, 20]
          exclude:
            - node-v: 16
              os: macos-latest
  
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Setup Node Version - ${{ matrix.node-v }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-v }}
  
        - name: Install Dependencies
          run: npm install
  
        - name: Unit Testing
          run: npm test
  
        # - name: Delete Existing Artifact
        #   if: always()
        #   run: |
        #     echo "Checking for existing artifacts..."
        #     if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=Mocha%20Test%20Result" | grep -q "id"; then
        #       artifact_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=Mocha%20Test%20Result" | jq -r ".artifacts[0].id")
        #       echo "Deleting existing artifact with ID $artifact_id..."
        #       curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id"
        #     else
        #       echo "No existing artifact found."
        #     fi
  
        # - name: Archive Test Result
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: Mocha Test Result
        #     path: test-results.xml

    #hbh 
  